import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import Navigation from "@/components/Navigation";

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-background to-muted">
      <Navigation />
      
      <div className="container mx-auto px-4 py-16 max-w-4xl">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
              Terms of Service
            </span>
          </h1>
          <p className="text-lg text-muted-foreground">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>

        <div className="space-y-8">
          <Card>
            <CardHeader>
              <CardTitle>Acceptance of Terms</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                By accessing or using Createa ("the Service"), you agree to be bound by these Terms of Service 
                ("Terms"). If you disagree with any part of these terms, you may not access the Service.
              </p>
              <p>
                These Terms apply to all visitors, users, and others who access or use the Service.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Description of Service</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                Createa is an AI-powered platform that generates web animations based on natural language 
                descriptions. The Service allows users to:
              </p>
              <ul>
                <li>Create animations using text prompts</li>
                <li>Generate code in various frameworks (CSS, JavaScript, React, etc.)</li>
                <li>Preview and customize generated animations</li>
                <li>Export production-ready code</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>User Accounts</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                To access certain features of the Service, you must create an account. You agree to:
              </p>
              <ul>
                <li>Provide accurate, current, and complete information</li>
                <li>Maintain and update your account information</li>
                <li>Keep your password secure and confidential</li>
                <li>Notify us immediately of any unauthorized access</li>
                <li>Accept responsibility for all activities under your account</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Acceptable Use</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>You agree not to use the Service to:</p>
              <ul>
                <li>Generate content that is illegal, harmful, or violates any laws</li>
                <li>Create animations for malicious purposes (malware, phishing, etc.)</li>
                <li>Attempt to reverse engineer or copy our AI technology</li>
                <li>Overload our systems with excessive requests</li>
                <li>Violate the intellectual property rights of others</li>
                <li>Harass, abuse, or harm other users</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Intellectual Property Rights</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                <strong>Your Content:</strong> You retain ownership of the prompts and descriptions you provide. 
                However, you grant us a license to use this content to provide and improve the Service.
              </p>
              <p>
                <strong>Generated Code:</strong> You have full rights to use, modify, and distribute the code 
                generated by our Service for any lawful purpose, including commercial use.
              </p>
              <p>
                <strong>Our Technology:</strong> The Service, including our AI models, algorithms, and platform, 
                is proprietary and protected by intellectual property laws.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Payment and Billing</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                Certain features of the Service may require payment. By providing payment information, you:
              </p>
              <ul>
                <li>Authorize us to charge the specified fees</li>
                <li>Agree to pay all applicable taxes</li>
                <li>Understand that fees are non-refundable except as required by law</li>
                <li>Accept that we may change pricing with advance notice</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Service Availability</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                We strive to provide reliable service but cannot guarantee:
              </p>
              <ul>
                <li>100% uptime or uninterrupted access</li>
                <li>Error-free operation of the Service</li>
                <li>Compatibility with all devices or browsers</li>
                <li>Permanent storage of your data</li>
              </ul>
              <p>
                We reserve the right to modify, suspend, or discontinue the Service at any time.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Limitation of Liability</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                To the maximum extent permitted by law, Createa shall not be liable for any indirect, 
                incidental, special, consequential, or punitive damages, including but not limited to:
              </p>
              <ul>
                <li>Loss of profits, data, or business opportunities</li>
                <li>Damages resulting from use of generated code</li>
                <li>Service interruptions or errors</li>
                <li>Third-party actions or content</li>
              </ul>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Termination</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                We may terminate or suspend your account and access to the Service:
              </p>
              <ul>
                <li>For violation of these Terms</li>
                <li>For fraudulent or illegal activity</li>
                <li>If required by law or legal process</li>
                <li>At our sole discretion for any reason</li>
              </ul>
              <p>
                You may terminate your account at any time by contacting us or using account settings.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Changes to Terms</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                We reserve the right to modify these Terms at any time. We will notify users of material 
                changes via email or through the Service. Continued use of the Service after changes 
                constitutes acceptance of the new Terms.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-neutral dark:prose-invert max-w-none">
              <p>
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <ul>
                <li>Email: legal@createa.app</li>
                <li>Address: [Your Company Address]</li>
              </ul>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;